param()

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

$repoRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
Set-Location $repoRoot
$venvPy = "$repoRoot\.venv\Scripts\python.exe"

if (-not (Test-Path $venvPy)) {
    throw "Virtual environment interpreter not found at $venvPy. Run install.ps1 first."
}

function Invoke-CheckedCommand {
    param(
        [string]$Executable,
        [string[]]$Arguments
    )

    & $Executable @Arguments
    if ($LASTEXITCODE -ne 0) {
        throw "Command failed: $Executable $($Arguments -join ' ')"
    }
}

function Invoke-Step {
    param(
        [string]$Name,
        [scriptblock]$Action
    )

    Write-Output "==> $Name"
    & $Action
}

function Invoke-PoetryCommand {
    param([string[]]$Arguments)

    Invoke-CheckedCommand $venvPy (@("-m", "poetry") + $Arguments)
}

Invoke-Step "Install Poetry" {
    Invoke-CheckedCommand $venvPy @("-m", "pip", "install", "poetry==2.4.1")
}

Invoke-Step "Install dev dependencies" {
    Invoke-PoetryCommand @("-v", "install", "--only", "dev", "--no-root")
}

Invoke-Step "Run PowerShell Lint" {
    if (-not (Get-Module -ListAvailable -Name PSScriptAnalyzer)) {
        Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force | Out-Null
        Install-Module -Name PSScriptAnalyzer -Scope CurrentUser -Force -AllowClobber
    }

    Import-Module PSScriptAnalyzer

    $settingsPath = Join-Path $repoRoot "tools\psscriptanalyzer.settings.psd1"
    if (-not (Test-Path $settingsPath)) {
        throw "PSScriptAnalyzer settings file not found: $settingsPath"
    }

    $psScripts = @(
        (Join-Path $repoRoot "install.ps1"),
        (Join-Path $repoRoot "run_pipeline_localy.ps1")
    )

    $issues = @()
    foreach ($scriptPath in $psScripts) {
        if (-not (Test-Path $scriptPath)) {
            throw "PowerShell script not found: $scriptPath"
        }

        $issues += Invoke-ScriptAnalyzer -Path $scriptPath -Settings $settingsPath
    }

    if ($issues.Count -gt 0) {
        $issues | Select-Object RuleName, Severity, ScriptName, Line, Message | Format-Table -AutoSize
        throw "PowerShell lint failed with $($issues.Count) issue(s)."
    }
}

Invoke-Step "Run Ruff" {
    Invoke-PoetryCommand @("run", "ruff", "check", ".")
}

Invoke-Step "Run Flake8" {
    Invoke-PoetryCommand @("run", "flake8", ".")
}

Invoke-Step "Run Pylint" {
    Invoke-PoetryCommand @("run", "pylint", "auto_deinterlancer.py", "modules", ".github/scripts")
}

Invoke-Step "Run tests with coverage" {
    if (-not (Test-Path "assets")) {
        New-Item -ItemType Directory -Path "assets" | Out-Null
    }

    $previousSkipFlag = $env:AUTO_VHS_SKIP_HW_DETECT
    $env:AUTO_VHS_SKIP_HW_DETECT = "1"
    try {
        Invoke-PoetryCommand @(
            "run",
            "pytest",
            "tests/"
        )
    }
    finally {
        if ($null -eq $previousSkipFlag) {
            Remove-Item Env:AUTO_VHS_SKIP_HW_DETECT -ErrorAction SilentlyContinue
        }
        else {
            $env:AUTO_VHS_SKIP_HW_DETECT = $previousSkipFlag
        }
    }
}

Invoke-Step "Enforce Per-File Coverage >= 90%" {
    if (-not (Test-Path "assets/coverage.xml")) {
        throw "assets/coverage.xml was not generated by pytest"
    }

    Invoke-PoetryCommand @(
        "run",
        "python",
        ".github/scripts/enforce_per_file_coverage.py",
        "assets/coverage.xml",
        "90"
    )
}

Invoke-Step "Generate coverage badge" {
    if (-not (Test-Path "assets")) {
        New-Item -ItemType Directory -Path "assets" | Out-Null
    }

    if (-not (Test-Path "assets/coverage.xml")) {
        throw "assets/coverage.xml was not generated by pytest"
    }

    Invoke-PoetryCommand @("run", "genbadge", "coverage", "-i", "assets/coverage.xml", "-o", "assets/coverage.svg")
    Write-Output "Badge updated: assets/coverage.svg"
}

Write-Output "Local pipeline completed successfully."

